# Generated by Django 4.2.21 on 2025-06-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecrew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='moviecrew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.person'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='metadata_ge_name_995fea_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['movie', 'role'], name='metadata_mo_movie_i_06157a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'person', 'role')},
        ),
    ]
