# Generated by Django 4.2.21 on 2025-06-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL
            """
            CREATE EXTENSION IF NOT EXISTS pg_trgm;

            CREATE INDEX IF NOT EXISTS idx_genre_name_trgm
            ON metadata_genre USING gin (name gin_trgm_ops);

            CREATE INDEX IF NOT EXISTS idx_person_name_trgm
            ON metadata_person USING gin (name gin_trgm_ops);
            """,
            # Reverse SQL
            """
            DROP INDEX IF EXISTS idx_genre_name_trgm;
            DROP INDEX IF EXISTS idx_person_name_trgm;
            DROP EXTENSION IF EXISTS pg_trgm;
            """
        ),
    ]
