# Generated by Django 4.2.21 on 2025-06-03 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20250601_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecrew',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['slug'], name='metadata_ge_slug_f1bda5_idx'),
        ),
    ]
