# Generated by Django 4.2.21 on 2025-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0004_moviecrew_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_vi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="genre",
            unique_together={("name", "language")},
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(
                fields=["language"], name="metadata_ge_languag_ee28cf_idx"
            ),
        ),
    ]
