# Generated by Django 4.2.21 on 2025-06-17 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0005_genre_language_genre_name_en_genre_name_vi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="name_vi",
        ),
    ]
