# Generated by Django 4.2.21 on 2025-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0011_fix_genre_summary_count_issue"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(fields=["language", "name"], name="idx_genre_lang_name"),
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(fields=["language", "slug"], name="idx_genre_lang_slug"),
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(
                condition=models.Q(("language__isnull", False)),
                fields=["language"],
                name="idx_genre_lang_with_movies",
            ),
        ),
        migrations.AddIndex(
            model_name="genresummary",
            index=models.Index(fields=["language"], name="idx_genresummary_language"),
        ),
        migrations.AddIndex(
            model_name="genresummary",
            index=models.Index(
                fields=["language", "movie_count"], name="idx_genresummary_lang_count"
            ),
        ),
        migrations.AddIndex(
            model_name="genresummary",
            index=models.Index(
                fields=["last_updated"], name="idx_genresummary_updated"
            ),
        ),
    ]
