# Generated by Django 4.2.23 on 2025-06-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("prenium_basic", "Prenium Basic"),
                    ("prenium_standard", "Prenium Standard"),
                    ("prenium_vip", "Prenium VIP"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
