# Generated by Django 4.2.21 on 2025-06-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL
            """
            CREATE INDEX IF NOT EXISTS idx_user_username_trgm
            ON users_users USING gin (username gin_trgm_ops);
            """,
            # Reverse SQL
            """
            DROP INDEX IF EXISTS idx_user_username_trgm;
            """
        ),
    ]
