# Generated by Django 4.2.21 on 2025-06-21 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_subscription_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription_end_date",
        ),
    ]
