# Generated by Django 4.2.21 on 2025-06-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_token_expiry',
        ),
    ]
