# Generated by Django 4.2.21 on 2025-06-26 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_fix_user_type_typo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserMovieRating",
        ),
    ]
