# Generated by Django 4.2.21 on 2025-06-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_delete_usermovierating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_group",
            field=models.CharField(
                blank=True,
                help_text="Age group from MovieLens: Under 18, 18-24, 25-34, etc.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                blank=True,
                help_text="Occupation from MovieLens dataset",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True,
                help_text="Zip code from MovieLens dataset",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["age_group"], name="users_users_age_gro_b0a149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["occupation"], name="users_users_occupat_746bc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["zip_code"], name="users_users_zip_cod_a75c6f_idx"
            ),
        ),
    ]
