# Generated by Django 4.2.21 on 2025-06-30 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0025_reviewvote"),
        ("users", "0007_add_movielens_demographics_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_users_favorite_movies",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_users_user_id_d8005c_idx"
                    ),
                    models.Index(
                        fields=["movie"], name="users_users_movie_i_1d70c6_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_users_created_ab3ba2_idx"
                    ),
                ],
                "unique_together": {("user", "movie")},
            },
        ),
    ]
