# Generated by Django 4.2.21 on 2025-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_account',
            field=models.BooleanField(default=False),
        ),
    ]
