# Generated by Django 4.2.21 on 2025-07-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0027_fix_reply_constraint"),
        ("users", "0008_userfavoritemovie"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned to Watch"),
                            ("WATCHING", "Currently Watching"),
                            ("WATCHED", "Watched"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users_watchlistitem",
            },
        ),
        migrations.RemoveIndex(
            model_name="watchlist",
            name="users_watch_status_1b0a19_idx",
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="name",
            field=models.CharField(default="My Watchlist", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(fields=["name"], name="users_watch_name_7ac989_idx"),
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="users.watchlist",
            ),
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="status",
        ),
        migrations.AddIndex(
            model_name="watchlistitem",
            index=models.Index(
                fields=["watchlist"], name="users_watch_watchli_ebf147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlistitem",
            index=models.Index(fields=["movie"], name="users_watch_movie_i_8d7c40_idx"),
        ),
        migrations.AddIndex(
            model_name="watchlistitem",
            index=models.Index(fields=["status"], name="users_watch_status_71c01c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="watchlistitem",
            unique_together={("watchlist", "movie")},
        ),
    ]
