# Generated by Django 4.2.21 on 2025-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_watchlistitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfavoritegenre",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="userfavoritemovie",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="watchlist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="watchlistitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="watchlist",
            name="users_watch_name_7ac989_idx",
        ),
        migrations.RemoveIndex(
            model_name="watchlistitem",
            name="users_watch_watchli_ebf147_idx",
        ),
        migrations.RemoveIndex(
            model_name="watchlistitem",
            name="users_watch_movie_i_8d7c40_idx",
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("WATCHING", "Watching"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("DROPPED", "Dropped"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="userfavoritegenre",
            index=models.Index(fields=["user"], name="users_users_user_id_719ebc_idx"),
        ),
        migrations.AddIndex(
            model_name="userfavoritegenre",
            index=models.Index(fields=["genre"], name="users_users_genre_i_2147b8_idx"),
        ),
        migrations.AddIndex(
            model_name="userfavoritegenre",
            index=models.Index(
                fields=["created_at"], name="users_users_created_6a1ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["created_at"], name="users_watch_created_3af75e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlistitem",
            index=models.Index(
                fields=["watchlist", "movie"], name="users_watch_watchli_22025e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlistitem",
            index=models.Index(
                fields=["created_at"], name="users_watch_created_8e09d6_idx"
            ),
        ),
    ]
