# Generated by Django 4.2.21 on 2025-07-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_userfavoritegenre_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Birth date for automatic age calculation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                blank=True, help_text="Auto-calculated from birth_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Under 18", "Under 18"),
                    ("18-24", "18-24"),
                    ("25-34", "25-34"),
                    ("35-44", "35-44"),
                    ("45-49", "45-49"),
                    ("50-55", "50-55"),
                    ("56+", "56+"),
                ],
                help_text="Age group auto-calculated from birth_date",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("other", "Other"),
                    ("academic/educator", "Academic/Educator"),
                    ("artist", "Artist"),
                    ("clerical/admin", "Clerical/Admin"),
                    ("college/grad student", "College/Grad Student"),
                    ("customer service", "Customer Service"),
                    ("doctor/health care", "Doctor/Health Care"),
                    ("executive/managerial", "Executive/Managerial"),
                    ("farmer", "Farmer"),
                    ("homemaker", "Homemaker"),
                    ("K-12 student", "K-12 Student"),
                    ("lawyer", "Lawyer"),
                    ("programmer", "Programmer"),
                    ("retired", "Retired"),
                    ("sales/marketing", "Sales/Marketing"),
                    ("scientist", "Scientist"),
                    ("self-employed", "Self-employed"),
                    ("technician/engineer", "Technician/Engineer"),
                    ("tradesman/craftsman", "Tradesman/Craftsman"),
                    ("unemployed", "Unemployed"),
                    ("writer", "Writer"),
                ],
                help_text="Occupation from MovieLens dataset",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True,
                help_text="Zip code from user input",
                max_length=10,
                null=True,
            ),
        ),
    ]
