# Generated by Django 4.2.21 on 2025-07-28 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_add_birth_date_and_profile_completion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="commentlike",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="commentlike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="CommentLike",
        ),
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
    ]
