# Generated by Django 4.2.21 on 2025-07-26 15:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0048_movie_idx_mv_pstr_adlt_ttl_rt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("recommendation_type", models.CharField(max_length=20)),
                ("total_recommendations", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("unique_movies", models.IntegerField(default=0)),
                ("average_predicted_rating", models.FloatField(default=0.0)),
                ("average_actual_rating", models.FloatField(default=0.0)),
                ("rmse", models.FloatField(default=0.0)),
                ("mae", models.FloatField(default=0.0)),
                ("click_through_rate", models.FloatField(default=0.0)),
                ("conversion_rate", models.FloatField(default=0.0)),
                ("average_rating_given", models.FloatField(default=0.0)),
                ("intra_list_diversity", models.FloatField(default=0.0)),
                ("novelty_score", models.FloatField(default=0.0)),
                ("catalog_coverage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendations_metrics",
                "indexes": [
                    models.Index(
                        fields=["date", "recommendation_type"],
                        name="recommendat_date_38e892_idx",
                    ),
                    models.Index(
                        fields=["click_through_rate"],
                        name="recommendat_click_t_ef6d7e_idx",
                    ),
                    models.Index(
                        fields=["conversion_rate"],
                        name="recommendat_convers_f5fc92_idx",
                    ),
                ],
                "unique_together": {("date", "recommendation_type")},
            },
        ),
        migrations.CreateModel(
            name="DemographicCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("age_range_min", models.IntegerField(blank=True, null=True)),
                ("age_range_max", models.IntegerField(blank=True, null=True)),
                (
                    "primary_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("common_occupations", models.JSONField(blank=True, default=list)),
                ("geographic_regions", models.JSONField(blank=True, default=list)),
                (
                    "preferred_genres",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Average genre preferences for this cluster",
                    ),
                ),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_variance", models.FloatField(default=0.0)),
                ("user_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recommendations_demographic_cluster",
                "indexes": [
                    models.Index(
                        fields=["cluster_id"], name="recommendat_cluster_81cc15_idx"
                    ),
                    models.Index(
                        fields=["age_range_min", "age_range_max"],
                        name="recommendat_age_ran_462cc7_idx",
                    ),
                    models.Index(
                        fields=["primary_gender"], name="recommendat_primary_695bc3_idx"
                    ),
                    models.Index(
                        fields=["user_count"], name="recommendat_user_co_3fcf3e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_type",
                    models.CharField(
                        choices=[
                            ("collaborative", "Collaborative Filtering"),
                            ("demographic", "Demographic Similarity"),
                            ("behavioral", "Behavioral Similarity"),
                            ("hybrid", "Hybrid Similarity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Similarity score between -1 and 1",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("common_ratings_count", models.IntegerField(default=0)),
                (
                    "calculation_method",
                    models.CharField(default="pearson", max_length=50),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_user_similarity",
                "indexes": [
                    models.Index(
                        fields=["user1", "similarity_type", "similarity_score"],
                        name="recommendat_user1_i_d23175_idx",
                    ),
                    models.Index(
                        fields=["user2", "similarity_type", "similarity_score"],
                        name="recommendat_user2_i_5e40e4_idx",
                    ),
                    models.Index(
                        fields=["similarity_score", "confidence"],
                        name="recommendat_similar_187efd_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="recommendat_updated_3816e2_idx"
                    ),
                ],
                "unique_together": {("user1", "user2", "similarity_type")},
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Genre preference scores: {genre_id: score, ...}",
                    ),
                ),
                (
                    "actor_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Actor preference scores: {person_id: score, ...}",
                    ),
                ),
                (
                    "director_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Director preference scores: {person_id: score, ...}",
                    ),
                ),
                (
                    "year_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Release year preferences: {decade: score, ...}",
                    ),
                ),
                (
                    "demographic_cluster",
                    models.CharField(
                        blank=True,
                        help_text="Demographic cluster ID (calculated)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "behavior_cluster",
                    models.CharField(
                        blank=True,
                        help_text="Behavior cluster ID (calculated)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "novelty_preference",
                    models.FloatField(
                        default=0.5,
                        help_text="How much user likes new/unknown movies (0=popular only, 1=very novel)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "diversity_preference",
                    models.FloatField(
                        default=0.5,
                        help_text="How much user likes genre diversity (0=same genre, 1=very diverse)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "recency_preference",
                    models.FloatField(
                        default=0.5,
                        help_text="How much user prefers recent movies (0=any era, 1=recent only)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_variance", models.FloatField(default=0.0)),
                ("interaction_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_calculated", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_user_preference",
                "indexes": [
                    models.Index(
                        fields=["demographic_cluster"],
                        name="recommendat_demogra_9d9ea4_idx",
                    ),
                    models.Index(
                        fields=["behavior_cluster"],
                        name="recommendat_behavio_af7969_idx",
                    ),
                    models.Index(
                        fields=["rating_count"], name="recommendat_rating__b4dc14_idx"
                    ),
                    models.Index(
                        fields=["average_rating"], name="recommendat_average_3febc0_idx"
                    ),
                    models.Index(
                        fields=["last_calculated"],
                        name="recommendat_last_ca_64f56e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("collaborative", "Collaborative Filtering"),
                            ("demographic", "Demographic Filtering"),
                            ("content_based", "Content-Based"),
                            ("trending", "Trending"),
                            ("popular", "Popular"),
                            ("hybrid", "Hybrid Algorithm"),
                            ("similar_users", "Similar Users"),
                            ("genre_based", "Genre-Based"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage Recommendations"),
                            ("after_rating", "After Rating a Movie"),
                            ("profile", "Profile Page"),
                            ("genre_explorer", "Genre Explorer"),
                            ("similar_movies", "Similar Movies"),
                            ("onboarding", "User Onboarding"),
                        ],
                        default="homepage",
                        max_length=20,
                    ),
                ),
                (
                    "predicted_rating",
                    models.FloatField(
                        blank=True,
                        help_text="Predicted rating for this user",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Confidence in this recommendation",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "novelty_score",
                    models.FloatField(
                        default=0.5,
                        help_text="How novel/surprising this recommendation is",
                    ),
                ),
                ("rank", models.IntegerField(help_text="Rank in recommendation list")),
                ("score", models.FloatField(help_text="Final recommendation score")),
                (
                    "explanation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Explanation why this movie was recommended",
                    ),
                ),
                ("was_clicked", models.BooleanField(default=False)),
                ("was_rated", models.BooleanField(default=False)),
                ("was_watched", models.BooleanField(default=False)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("not_interested", "Not Interested"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 2, 15, 20, 10, 576134, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_result",
                "indexes": [
                    models.Index(
                        fields=["user", "recommendation_type", "rank"],
                        name="recommendat_user_id_e9718a_idx",
                    ),
                    models.Index(
                        fields=["user", "context", "rank"],
                        name="recommendat_user_id_c0b194_idx",
                    ),
                    models.Index(
                        fields=["score", "confidence_score"],
                        name="recommendat_score_d7aace_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="recommendat_created_1dc549_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="recommendat_expires_7e07c6_idx"
                    ),
                    models.Index(
                        fields=["was_clicked", "was_rated"],
                        name="recommendat_was_cli_f735d9_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "movie", "recommendation_type", "context")
                },
            },
        ),
        migrations.CreateModel(
            name="MovieSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_type",
                    models.CharField(
                        choices=[
                            ("content", "Content-Based"),
                            ("collaborative", "Collaborative"),
                            ("genre", "Genre Similarity"),
                            ("cast", "Cast Similarity"),
                            ("hybrid", "Hybrid Similarity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Similarity score between 0 and 1",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("genre_similarity", models.FloatField(default=0.0)),
                ("cast_similarity", models.FloatField(default=0.0)),
                ("director_similarity", models.FloatField(default=0.0)),
                ("year_similarity", models.FloatField(default=0.0)),
                ("rating_similarity", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_movie1",
                        to="movies.movie",
                    ),
                ),
                (
                    "movie2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_movie2",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_movie_similarity",
                "indexes": [
                    models.Index(
                        fields=["movie1", "similarity_type", "similarity_score"],
                        name="recommendat_movie1__29cfa5_idx",
                    ),
                    models.Index(
                        fields=["movie2", "similarity_type", "similarity_score"],
                        name="recommendat_movie2__7e6898_idx",
                    ),
                    models.Index(
                        fields=["similarity_score"],
                        name="recommendat_similar_bcbd48_idx",
                    ),
                    models.Index(
                        fields=["genre_similarity"],
                        name="recommendat_genre_s_79ca31_idx",
                    ),
                    models.Index(
                        fields=["cast_similarity"],
                        name="recommendat_cast_si_fc63a0_idx",
                    ),
                ],
                "unique_together": {("movie1", "movie2", "similarity_type")},
            },
        ),
    ]
