# Generated by Django 4.2.21 on 2025-07-28 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationresult",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 4, 6, 32, 37, 809070, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
