# Generated by Django 4.2.21 on 2025-07-31 12:11

import apps.recommendations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationresult",
            name="expires_at",
            field=models.DateTimeField(
                default=apps.recommendations.models.get_default_expires_at
            ),
        ),
    ]
