# Generated by Django 4.2.21 on 2025-08-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_alter_recommendationresult_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesimilarity",
            name="similarity_type",
            field=models.CharField(
                choices=[
                    ("collaborative", "Collaborative"),
                    ("genre", "Genre Similarity"),
                    ("cast", "Cast Similarity"),
                    ("hybrid", "Hybrid Similarity"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recommendationresult",
            name="recommendation_type",
            field=models.CharField(
                choices=[
                    ("collaborative", "Collaborative Filtering"),
                    ("demographic", "Demographic Filtering"),
                    ("trending", "Trending"),
                    ("popular", "Popular"),
                    ("hybrid", "Hybrid Algorithm"),
                    ("similar_users", "Similar Users"),
                    ("genre_based", "Genre-Based"),
                ],
                max_length=20,
            ),
        ),
    ]
