# Generated by Django 4.2.21 on 2025-07-28 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_alter_recommendationresult_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationresult",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 4, 10, 40, 40, 95216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
