# Generated by Django 4.2.21 on 2025-08-01 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0003_alter_moviesimilarity_similarity_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovieSimilarity",
        ),
    ]
