# Generated by Django 4.2.21 on 2025-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0004_remove_movie_similarity_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("model_data", models.BinaryField()),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Model Storage",
                "verbose_name_plural": "Model Storage",
                "db_table": "model_storage",
            },
        ),
    ]
