# Generated by Django 4.2.21 on 2025-08-25 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0005_modelstorage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userpreference",
            name="recommendat_behavio_af7969_idx",
        ),
        migrations.RemoveIndex(
            model_name="userpreference",
            name="recommendat_rating__b4dc14_idx",
        ),
        migrations.RemoveIndex(
            model_name="userpreference",
            name="recommendat_average_3febc0_idx",
        ),
        migrations.RemoveIndex(
            model_name="userpreference",
            name="recommendat_last_ca_64f56e_idx",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="actor_preferences",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="behavior_cluster",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="director_preferences",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="diversity_preference",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="genre_preferences",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="interaction_count",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="last_calculated",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="novelty_preference",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="rating_variance",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="recency_preference",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="year_preferences",
        ),
    ]
