# Generated by Django 4.2.21 on 2025-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "recommendations",
            "0006_remove_userpreference_recommendat_behavio_af7969_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demographiccluster",
            name="geographic_regions",
        ),
    ]
