# Generated by Django 4.2.21 on 2025-08-25 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0007_remove_demographiccluster_geographic_regions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recommendationresult",
            name="recommendat_was_cli_f735d9_idx",
        ),
        migrations.RemoveField(
            model_name="recommendationresult",
            name="user_feedback",
        ),
        migrations.RemoveField(
            model_name="recommendationresult",
            name="was_clicked",
        ),
        migrations.RemoveField(
            model_name="recommendationresult",
            name="was_rated",
        ),
        migrations.RemoveField(
            model_name="recommendationresult",
            name="was_watched",
        ),
    ]
