# Generated by Django 4.2.21 on 2025-06-21 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = []
