# Generated by Django 4.2.21 on 2025-06-21 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        # Drop the old foreign key constraint
        migrations.RunSQL(
            sql="""
            ALTER TABLE subscriptions_paymenttransaction
            DROP CONSTRAINT IF EXISTS subscriptions_paymen_user_id_931e323d_fk_auth_user;
            """,
            reverse_sql="""
            ALTER TABLE subscriptions_paymenttransaction
            ADD CONSTRAINT subscriptions_paymen_user_id_931e323d_fk_auth_user
            FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE;
            """
        ),
        # Add the new foreign key constraint pointing to users_users
        migrations.RunSQL(
            sql="""
            ALTER TABLE subscriptions_paymenttransaction
            ADD CONSTRAINT subscriptions_paymenttransaction_user_id_fk
            FOREIGN KEY (user_id) REFERENCES users_users(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE subscriptions_paymenttransaction
            DROP CONSTRAINT IF EXISTS subscriptions_paymenttransaction_user_id_fk;
            """
        ),
    ]
