# Generated by Django 4.2.21 on 2025-06-21 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_auto_20250621_1219"),
    ]

    operations = [
        # Force drop the problematic foreign key constraint
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Drop the constraint if it exists
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints
                    WHERE constraint_name = 'subscriptions_paymen_user_id_931e323d_fk_auth_user'
                ) THEN
                    ALTER TABLE subscriptions_paymenttransaction
                    DROP CONSTRAINT subscriptions_paymen_user_id_931e323d_fk_auth_user;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- No reverse needed as we're fixing a broken constraint
            """
        ),
        # Add the correct foreign key constraint
        migrations.RunSQL(
            sql="""
            ALTER TABLE subscriptions_paymenttransaction
            ADD CONSTRAINT subscriptions_paymenttransaction_user_id_fk_users
            FOREIGN KEY (user_id) REFERENCES users_users(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE subscriptions_paymenttransaction
            DROP CONSTRAINT IF EXISTS subscriptions_paymenttransaction_user_id_fk_users;
            """
        ),
    ]
