# Generated by Django 5.1.7 on 2025-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='metadata.genre')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='movies_movi_title_652549_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'), models.Index(fields=['imdb_rating'], name='movies_movi_imdb_ra_8e4972_idx')],
            },
        ),
    ]
