# Generated by Django 5.1.7 on 2025-03-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSimilarity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_movie1', to='movies.movie')),
                ('movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_movie2', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('algorithm_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='movies.movie')),
            ],
        ),
    ]
