# Generated by Django 5.1.7 on 2025-03-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.users'),
        ),
        migrations.AddField(
            model_name='usersimilarity',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_user1', to='users.users'),
        ),
        migrations.AddField(
            model_name='usersimilarity',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_user2', to='users.users'),
        ),
        migrations.AlterUniqueTogether(
            name='moviesimilarity',
            unique_together={('movie1', 'movie2')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user'], name='recommendat_user_id_39fd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['score'], name='recommendat_score_46bfe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersimilarity',
            unique_together={('user1', 'user2')},
        ),
    ]
