# Generated by Django 5.1.7 on 2025-03-16 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id_movie_movies_movi_tmdb_id_0e4cad_idx'),
        ('recommendations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('source', models.CharField(choices=[('movielens', 'MovieLens'), ('user', 'User'), ('tmdb', 'TMDB')], default='movielens', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'movie'], name='recommendat_user_id_861d98_idx'), models.Index(fields=['movie', 'score'], name='recommendat_movie_i_73b1e3_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
