const mockReviews = [
  {
    id: 1,
    movieTitle: 'Inception',
    rating: 4,
    userName: 'Alex Johnson',
    userAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    date: 'May 18',
    text: "One of the best movies I've ever seen. The concept is mind-blowing and the execution is...",
    likes: 18,
    comments: 2,
  },
  {
    id: 2,
    movieTitle: 'The Shawshank Redemption',
    rating: 4,
    userName: 'Sam Smith',
    userAvatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    date: 'May 20',
    text: 'Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit...Great movie with amazing visuals and a complex plot. Sometimes it gets a bit... ',
    likes: 14,
    comments: 0,
  },
  {
    id: 3,
    movieTitle: 'The Dark Knight',
    rating: 4,
    userName: 'Taylor Wong',
    userAvatar: 'https://randomuser.me/api/portraits/men/65.jpg',
    date: 'May 17',
    text: "The soundtrack, the acting, the story - everything is perfect. I've watched it multiple times and s...",
    likes: 49,
    comments: 4,
  },
  {
    id: 4,
    movieTitle: 'Pulp Fiction',
    rating: 4,
    userName: 'Jordan Lee',
    userAvatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    date: 'May 17',
    text: "One of the best movies I've ever seen. The concept is mind-blowing and the execution is...",
    likes: 43,
    comments: 5,
  },
  {
    id: 6,
    movieTitle: 'Inception',
    rating: 4,
    userName: 'Alex Johnson',
    userAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    date: 'May 18',
    text: "One of the best movies I've ever seen. The concept is mind-blowing and the execution is...",
    likes: 18,
    comments: 2,
  },
  {
    id: 7,
    movieTitle: 'The Shawshank Redemption',
    rating: 4,
    userName: 'Sam Smith',
    userAvatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    date: 'May 20',
    text: 'Great movie with amazing visuals and a complex plot. Sometimes it gets a bit... ',
    likes: 14,
    comments: 0,
  },
  {
    id: 8,
    movieTitle: 'The Dark Knight',
    rating: 4,
    userName: 'Taylor Wong',
    userAvatar: 'https://randomuser.me/api/portraits/men/65.jpg',
    date: 'May 17',
    text: "The soundtrack, the acting, the story - everything is perfect. I've watched it multiple times and s...",
    likes: 49,
    comments: 4,
  },
  {
    id: 9,
    movieTitle: 'Pulp Fiction',
    rating: 4,
    userName: 'Jordan Lee',
    userAvatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    date: 'May 17',
    text: "One of the best movies I've ever seen. The concept is mind-blowing and the execution is...",
    likes: 43,
    comments: 5,
  },
];

export default mockReviews;
