# Generated by Django 4.2.21 on 2025-06-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20250601_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('review_id', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(default='IMDB', max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
            ],
            options={
                'db_table': 'movies_review',
                'indexes': [models.Index(fields=['movie', 'rating'], name='movies_revi_movie_i_205ca7_idx'), models.Index(fields=['username'], name='movies_revi_usernam_d336b2_idx'), models.Index(fields=['published_at'], name='movies_revi_publish_bc4460_idx'), models.Index(fields=['review_id'], name='movies_revi_review__9a7f44_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('metacritic_rating', models.IntegerField(blank=True, null=True)),
                ('rotten_tomatoes_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rotten_tomatoes_votes', models.IntegerField(blank=True, null=True)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tmdb_votes', models.IntegerField(blank=True, null=True)),
                ('film_affinity_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('film_affinity_votes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
            ],
            options={
                'db_table': 'movies_rating',
                'indexes': [models.Index(fields=['imdb_rating'], name='movies_rati_imdb_ra_24b433_idx'), models.Index(fields=['metacritic_rating'], name='movies_rati_metacri_b6685f_idx'), models.Index(fields=['rotten_tomatoes_rating'], name='movies_rati_rotten__9caa34_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('WRITER', 'Writer'), ('ACTOR', 'Actor'), ('PRODUCER', 'Producer'), ('CINEMATOGRAPHER', 'Cinematographer'), ('EDITOR', 'Editor'), ('COMPOSER', 'Composer')], max_length=50)),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movies.movie')),
            ],
            options={
                'db_table': 'movies_cast',
                'indexes': [models.Index(fields=['movie', 'order'], name='movies_cast_movie_i_27d093_idx'), models.Index(fields=['name'], name='movies_cast_name_c00028_idx'), models.Index(fields=['imdb_id'], name='movies_cast_imdb_id_e141db_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieBoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('domestic_gross', models.BigIntegerField(blank=True, null=True)),
                ('foreign_gross', models.BigIntegerField(blank=True, null=True)),
                ('worldwide_gross', models.BigIntegerField(blank=True, null=True)),
                ('opening_weekend_gross', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='box_office', to='movies.movie')),
            ],
            options={
                'db_table': 'movies_boxoffice',
                'indexes': [models.Index(fields=['budget'], name='movies_boxo_budget_0e5482_idx'), models.Index(fields=['domestic_gross'], name='movies_boxo_domesti_aa319e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('won', models.BooleanField(default=False)),
                ('nomination', models.BooleanField(default=False)),
                ('is_prestigious', models.BooleanField(default=False)),
                ('award_event', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='movies.movie')),
            ],
            options={
                'db_table': 'movies_award',
                'indexes': [models.Index(fields=['movie', 'year'], name='movies_awar_movie_i_b5df1a_idx'), models.Index(fields=['name', 'category'], name='movies_awar_name_3efd37_idx'), models.Index(fields=['is_prestigious'], name='movies_awar_is_pres_7b2bd3_idx')],
            },
        ),
    ]
