# Generated by Django 4.2.21 on 2025-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_moviereview_movierating_moviecast_movieboxoffice_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="movies_movi_imdb_ra_8e4972_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movies_movi_tmdb_id_0e4cad_idx",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="tmdb_id",
            new_name="imdb_id",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdb_rating",
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["imdb_id"], name="movies_movi_imdb_id_d04af4_idx"
            ),
        ),
    ]
