# Generated by Django 4.2.21 on 2025-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_remove_movie_movies_movi_imdb_ra_8e4972_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_top_rated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_upcoming",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="last_synced",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RUMORED", "Rumored"),
                    ("PLANNED", "Planned"),
                    ("IN_PRODUCTION", "In Production"),
                    ("POST_PRODUCTION", "Post Production"),
                    ("RELEASED", "Released"),
                    ("UPCOMING", "Upcoming"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["is_popular"], name="movies_movi_is_popu_70f3ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["is_top_rated"], name="movies_movi_is_top__eb80db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["is_upcoming"], name="movies_movi_is_upco_60faa8_idx"
            ),
        ),
    ]
