# Generated by Django 4.2.21 on 2025-06-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_movie_is_popular_movie_is_top_rated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="adult",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_adult",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="MovieAlternativeTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("region", models.CharField(blank=True, max_length=10, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("is_original", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
            options={
                "db_table": "movies_alternative_title",
            },
        ),
    ]
