# Generated by Django 4.2.21 on 2025-06-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_movie_adult_movie_end_year_movie_is_adult_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviecast",
            options={
                "verbose_name": "Cast Member",
                "verbose_name_plural": "Cast Members",
            },
        ),
        migrations.RemoveIndex(
            model_name="moviecast",
            name="movies_cast_movie_i_27d093_idx",
        ),
        migrations.RemoveIndex(
            model_name="moviecast",
            name="movies_cast_name_c00028_idx",
        ),
        migrations.RenameField(
            model_name="moviecast",
            old_name="character",
            new_name="main_character",
        ),
        migrations.AddField(
            model_name="moviealternativetitle",
            name="attributes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="moviealternativetitle",
            name="is_original_title",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moviealternativetitle",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moviealternativetitle",
            name="types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="all_characters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="moviealternativetitle",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_titles",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="moviecast",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="moviealternativetitle",
            unique_together={("movie", "title", "region", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="moviecast",
            unique_together={("movie", "imdb_id", "order")},
        ),
        migrations.AddIndex(
            model_name="moviealternativetitle",
            index=models.Index(fields=["movie"], name="movies_alte_movie_i_cf0001_idx"),
        ),
        migrations.AddIndex(
            model_name="moviealternativetitle",
            index=models.Index(fields=["region"], name="movies_alte_region_0670ed_idx"),
        ),
        migrations.AddIndex(
            model_name="moviealternativetitle",
            index=models.Index(
                fields=["language"], name="movies_alte_languag_640657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moviecast",
            index=models.Index(fields=["movie"], name="movies_cast_movie_i_e77d91_idx"),
        ),
        migrations.AddIndex(
            model_name="moviecast",
            index=models.Index(fields=["role"], name="movies_cast_role_7c2e01_idx"),
        ),
    ]
