# Generated by Django 4.2.21 on 2025-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_alter_moviecast_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
