# Generated by Django 4.2.21 on 2025-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_alter_movie_imdb_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="overview",
            new_name="overview_vi",
        ),
        migrations.AddField(
            model_name="movie",
            name="overview_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
