# Generated by Django 4.2.21 on 2025-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_rename_overview_movie_overview_vi_movie_overview_en"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="movies_movi_title_652549_idx",
        ),
        migrations.AddField(
            model_name="movie",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="title_vi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["title_en"], name="movies_movi_title_e_866870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["title_vi"], name="movies_movi_title_v_2ec4d4_idx"
            ),
        ),
    ]
