# Generated by Django 4.2.21 on 2025-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0010_remove_movie_movies_movi_title_652549_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="last_genre_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="last_title_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(
                help_text="Default title (usually in English)", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["slug"], name="movies_movi_slug_5ef9c7_idx"),
        ),
    ]
