# Generated by Django 4.2.21 on 2025-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0011_movie_last_genre_sync_movie_last_title_sync_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # Drop existing indexes if they exist
            """
            DROP INDEX IF EXISTS movies_movi_tmdb_id_0e4cad_idx;
            DROP INDEX IF EXISTS movies_movie_tmdb_id_a5a63d6d_like;
            """,
            # No reverse SQL needed
            reverse_sql=""
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["tmdb_id"], name="movies_movi_tmdb_id_0e4cad_idx"
            ),
        ),
    ]
