# Generated by Django 4.2.23 on 2025-06-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_add_tmdb_id_again"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movietrailer",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trailers",
                to="movies.movie",
            ),
        ),
    ]
