# Generated by Django 4.2.21 on 2025-06-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0015_remove_old_poster_url_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["poster_url"], name="idx_movie_poster_v2"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["poster_url", "release_date"], name="idx_movie_poster_rel_v2"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(("poster_url__isnull", False)),
                fields=["poster_url"],
                name="idx_movie_poster_nn_v2",
            ),
        ),
    ]
