# Generated by Django 5.1.3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_add_poster_url_indexes_v2'),
    ]

    operations = [
        # Add cached rating fields to Movie model
        migrations.AddField(
            model_name='movie',
            name='cached_imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cached IMDB rating for fast filtering/sorting', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cached_imdb_votes',
            field=models.IntegerField(blank=True, help_text='Cached IMDB votes for fast filtering/sorting', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cached_tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cached TMDB rating for fast filtering/sorting', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cached_tmdb_votes',
            field=models.IntegerField(blank=True, help_text='Cached TMDB votes for fast filtering/sorting', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='combined_rating_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weighted average of all ratings', max_digits=4, null=True),
        ),

        # Add basic indexes for cached rating fields
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_cached_imdb_rating
        #        ON movies_movie (cached_imdb_rating);""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_cached_imdb_rating;"
        # ),
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_cached_tmdb_rating
        #        ON movies_movie (cached_tmdb_rating);""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_cached_tmdb_rating;"
        # ),
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_combined_rating
        #        ON movies_movie (combined_rating_score);""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_combined_rating;"
        # ),

        # Add basic performance indexes
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_runtime
        #        ON movies_movie (runtime) WHERE runtime IS NOT NULL;""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_runtime;"
        # ),
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_adult
        #        ON movies_movie (adult);""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_adult;"
        # ),
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_status_rating
        #        ON movies_movie (status, cached_imdb_rating);""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_status_rating;"
        # ),
        # migrations.RunSQL(
        #     """CREATE INDEX IF NOT EXISTS idx_movie_poster_with_rating
        #        ON movies_movie (poster_url, cached_imdb_rating)
        #        WHERE poster_url IS NOT NULL AND poster_url != '';""",
        #     reverse_sql="DROP INDEX IF EXISTS idx_movie_poster_with_rating;"
        # ),
    ]
