# Generated by Django 4.2.21 on 2025-06-26 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0017_optimize_search_performance"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moviereview",
            name="movies_revi_usernam_d336b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="moviereview",
            name="movies_revi_publish_bc4460_idx",
        ),
        migrations.RemoveIndex(
            model_name="moviereview",
            name="movies_revi_review__9a7f44_idx",
        ),
        migrations.RemoveField(
            model_name="moviereview",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="moviereview",
            name="review_id",
        ),
        migrations.RemoveField(
            model_name="moviereview",
            name="username",
        ),
        migrations.AddField(
            model_name="moviecast",
            name="biography",
            field=models.TextField(
                blank=True, help_text="Biography from TMDB", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="birth_year",
            field=models.IntegerField(
                blank=True, help_text="Birth year from IMDB", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="death_year",
            field=models.IntegerField(
                blank=True, help_text="Death year from IMDB", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="gender",
            field=models.IntegerField(
                blank=True, help_text="Gender from TMDB (1=Female, 2=Male)", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="known_for_titles",
            field=models.JSONField(
                blank=True, default=list, help_text="Known movie titles from IMDB"
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="place_of_birth",
            field=models.CharField(
                blank=True, help_text="Birth place from TMDB", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="popularity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Popularity score from TMDB",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="primary_profession",
            field=models.JSONField(
                blank=True, default=list, help_text="Top-3 professions from IMDB"
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="profile_path",
            field=models.CharField(
                blank=True,
                help_text="Actor/Director profile image URL from TMDB",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="tmdb_id",
            field=models.IntegerField(
                blank=True, help_text="TMDB person ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="external_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Original publish date from external source",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="external_review_id",
            field=models.CharField(
                blank=True,
                help_text="Review ID from external source",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="external_username",
            field=models.CharField(
                blank=True,
                help_text="Username from external source (for EXTERNAL type)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Privacy setting for user reviews"
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="review_type",
            field=models.CharField(
                choices=[("USER", "User Review"), ("EXTERNAL", "External Review")],
                default="USER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Internal app user (for USER type reviews)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="moviereview",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Rating scale 0.0-5.0 (5-star system)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moviereview",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="External source name (IMDB, TMDB, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moviereview",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="URL to original review",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moviereview",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["poster_url", "release_date", "status"],
                name="idx_movie_poster_rel_status",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date", "poster_url"], name="idx_movie_rel_poster"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(
                    ("poster_url__isnull", False), ("poster_url__gt", "")
                ),
                fields=["release_date"],
                name="idx_movie_rel_with_poster",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["cached_imdb_rating"], name="idx_movie_cached_imdb_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["cached_imdb_votes"], name="idx_movie_cached_imdb_votes"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["cached_tmdb_rating"], name="idx_movie_cached_tmdb_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["combined_rating_score"], name="idx_movie_combined_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["runtime"], name="idx_movie_runtime"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["adult"], name="idx_movie_adult"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["status", "adult"], name="idx_movie_status_adult"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date", "status"], name="idx_movie_release_status"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["runtime", "status"], name="idx_movie_runtime_status"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(("poster_url__isnull", False)),
                fields=["poster_url", "cached_imdb_rating"],
                name="idx_movie_poster_rating",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(("poster_url__isnull", False)),
                fields=["poster_url", "release_date", "cached_imdb_rating"],
                name="idx_movie_poster_rel_rating",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["status", "cached_imdb_rating", "release_date"],
                name="idx_movie_status_rating_rel",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(
                    ("poster_url__isnull", False),
                    ("poster_url__gt", ""),
                    ("cached_imdb_rating__isnull", False),
                ),
                fields=["release_date", "cached_imdb_rating"],
                name="idx_movie_rel_rating_poster",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["release_date"], name="idx_movie_release_year"),
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(fields=["genre"], name="idx_moviegenre_genre"),
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(fields=["movie"], name="idx_moviegenre_movie"),
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(
                fields=["genre", "movie"], name="idx_moviegenre_genre_movie"
            ),
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(
                fields=["movie", "genre"], name="idx_moviegenre_movie_genre"
            ),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(fields=["movie"], name="movies_rati_movie_i_933b83_idx"),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["imdb_votes"], name="movies_rati_imdb_vo_96fc57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["tmdb_rating"], name="movies_rati_tmdb_ra_549e75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["tmdb_votes"], name="movies_rati_tmdb_vo_1d893a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["movie", "imdb_rating"], name="movies_rati_movie_i_00b84b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["movie", "tmdb_rating"], name="movies_rati_movie_i_c08863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["review_type", "created_at"],
                name="movies_revi_review__6f1cce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(fields=["user", "movie"], name="idx_user_movie_review"),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["external_review_id"], name="movies_revi_externa_34130f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(fields=["helpful_votes"], name="idx_helpful_votes"),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["movie", "review_type", "is_public"],
                name="movies_revi_movie_i_270829_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["created_at"], name="movies_revi_created_4f281e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(fields=["source"], name="movies_revi_source_2d344e_idx"),
        ),
    ]
