# Generated by Django 4.2.21 on 2025-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0018_remove_moviereview_movies_revi_usernam_d336b2_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="moviereview",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("external_username__isnull", True), ("user__isnull", False)
                    ),
                    models.Q(
                        ("external_username__isnull", False), ("user__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="review_user_xor_external",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviereview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review_type", "USER"), ("user__isnull", False)),
                fields=("user", "movie"),
                name="unique_user_movie_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviereview",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("review_type", "USER"),
                    models.Q(
                        ("external_review_id__isnull", False),
                        ("review_type", "EXTERNAL"),
                    ),
                    _connector="OR",
                ),
                name="external_review_must_have_id",
            ),
        ),
    ]
