# Generated by Django 4.2.21 on 2025-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0019_add_moviereview_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movielens_id",
            field=models.IntegerField(
                blank=True,
                help_text="MovieLens dataset ID for mapping",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Review language code (en, vi, etc.)",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["movielens_id"], name="movies_movi_moviele_552643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["language"], name="movies_revi_languag_fa4325_idx"
            ),
        ),
    ]
