# Generated by Django 4.2.21 on 2025-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0020_add_movielens_id_and_language_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["backdrop_url"], name="idx_movie_backdrop"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(("backdrop_url__isnull", False)),
                fields=["backdrop_url"],
                name="idx_movie_backdrop_nn",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["poster_url", "backdrop_url"], name="idx_movie_poster_backdrop"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(
                    ("backdrop_url__gt", ""),
                    ("backdrop_url__isnull", False),
                    ("poster_url__gt", ""),
                    ("poster_url__isnull", False),
                ),
                fields=["release_date"],
                name="idx_movie_rel_poster_backdrop",
            ),
        ),
    ]
