# Generated by Django 4.2.21 on 2025-06-29 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0021_add_backdrop_url_indexes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovieAlternativeTitle",
        ),
    ]
