# Generated by Django 4.2.21 on 2025-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0022_delete_moviealternativetitle"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["is_adult"], name="idx_movie_is_adult"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["status", "is_adult"], name="idx_movie_status_is_adult"
            ),
        ),
    ]
