# Generated by Django 4.2.21 on 2025-06-29 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0023_add_is_adult_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="idx_movie_adult",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="idx_movie_status_adult",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="adult",
        ),
    ]
