# Generated by Django 4.2.21 on 2025-06-29 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0024_remove_adult_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="movies.moviereview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "movies_review_vote",
                "indexes": [
                    models.Index(
                        fields=["review", "vote_type"],
                        name="movies_revi_review__eff6cc_idx",
                    ),
                    models.Index(
                        fields=["user", "vote_type"],
                        name="movies_revi_user_id_d46f6b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="movies_revi_created_5f6e48_idx"
                    ),
                ],
                "unique_together": {("review", "user")},
            },
        ),
    ]
