# Generated by Django 4.2.21 on 2025-07-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0025_reviewvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviereview",
            name="parent_review",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent review for replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="movies.moviereview",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["parent_review"], name="movies_revi_parent__702501_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="moviereview",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("parent_review__isnull", True),
                    models.Q(
                        ("parent_review__isnull", False), ("rating__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="replies_cannot_have_rating",
            ),
        ),
    ]
