# Generated by Django 4.2.21 on 2025-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0026_add_reply_system"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="moviereview",
            name="unique_user_movie_review",
        ),
        migrations.AddConstraint(
            model_name="moviereview",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("parent_review__isnull", True),
                    ("review_type", "USER"),
                    ("user__isnull", False),
                ),
                fields=("user", "movie"),
                name="unique_user_movie_review",
            ),
        ),
    ]
