# Generated by Django 4.2.21 on 2025-07-03 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0027_fix_reply_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviereview",
            options={"ordering": ["-created_at"]},
        ),
    ]
