# Generated by Django 4.2.21 on 2025-07-05 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0028_alter_moviereview_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviereview",
            name="is_approved",
            field=models.BooleanField(
                blank=True,
                help_text="Moderation status: True=approved, False=rejected, None=pending",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, help_text="When this review was moderated", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who moderated this review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="moderation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for moderation decision", null=True
            ),
        ),
    ]
