# Generated by Django 4.2.21 on 2025-07-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0029_add_moderation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("offensive", "Offensive Language"),
                            ("spam", "Spam or Advertising"),
                            ("abuse", "Abusive or Harassment"),
                            ("irrelevant", "Irrelevant Content"),
                            ("spoiler", "Contains Spoiler"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional additional details from reporter",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="movies.moviereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Report",
                "verbose_name_plural": "Review Reports",
                "db_table": "movies_review_report",
                "indexes": [
                    models.Index(
                        fields=["review"], name="movies_revi_review__32b8f7_idx"
                    ),
                    models.Index(
                        fields=["reported_by"], name="movies_revi_reporte_8602a5_idx"
                    ),
                    models.Index(
                        fields=["reason"], name="movies_revi_reason_bc46e3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="movies_revi_created_4c0281_idx"
                    ),
                ],
                "unique_together": {("review", "reported_by", "reason")},
            },
        ),
    ]
