# Generated by Django 4.2.21 on 2025-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0030_reviewreport"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["review_type", "is_public", "is_approved", "created_at"],
                name="idx_moderation_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["is_spoiler", "is_approved", "created_at"],
                name="idx_spoiler_moderation",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["moderated_by", "moderated_at"], name="idx_moderated_by_at"
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["is_approved", "created_at"], name="idx_approval_status"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["review", "created_at"], name="idx_report_moderation"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["reason", "created_at"], name="idx_report_reason_date"
            ),
        ),
    ]
