# Generated by Django 4.2.21 on 2025-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0031_add_moderation_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moviereview",
            name="idx_moderation_queue",
        ),
        migrations.RemoveIndex(
            model_name="moviereview",
            name="idx_spoiler_moderation",
        ),
        migrations.RemoveIndex(
            model_name="moviereview",
            name="idx_moderated_by_at",
        ),
        migrations.RemoveIndex(
            model_name="moviereview",
            name="idx_approval_status",
        ),
        migrations.RemoveIndex(
            model_name="reviewreport",
            name="idx_report_moderation",
        ),
        migrations.RemoveIndex(
            model_name="reviewreport",
            name="idx_report_reason_date",
        ),
        migrations.AddField(
            model_name="moviereview",
            name="auto_marked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="spoiler_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="spoiler_detected_patterns",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="spoiler_explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="spoiler_suggested_action",
            field=models.JSONField(blank=True, max_length=32, null=True),
        ),
    ]
