# Generated by Django 4.2.21 on 2025-07-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0032_remove_moviereview_idx_moderation_queue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereview",
            name="spoiler_suggested_action",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
