# Generated by Django 4.2.21 on 2025-07-07 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0033_alter_moviereview_spoiler_suggested_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_mark_threshold",
                    models.FloatField(
                        default=0.8,
                        help_text="Confidence threshold for auto-marking reviews as spoiler",
                    ),
                ),
                (
                    "flag_for_review_threshold",
                    models.FloatField(
                        default=0.6,
                        help_text="Confidence threshold for flagging reviews for manual review",
                    ),
                ),
                (
                    "suggest_warning_threshold",
                    models.FloatField(
                        default=0.4,
                        help_text="Confidence threshold for suggesting spoiler warning",
                    ),
                ),
                (
                    "learning_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable machine learning from moderator feedback",
                    ),
                ),
                (
                    "learning_rate",
                    models.FloatField(
                        default=0.1,
                        help_text="Learning rate for threshold adjustments (0.0-1.0)",
                    ),
                ),
                (
                    "min_feedback_count",
                    models.IntegerField(
                        default=10,
                        help_text="Minimum feedback count before applying threshold adjustments",
                    ),
                ),
                (
                    "auto_moderate_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic moderation based on thresholds",
                    ),
                ),
                (
                    "require_approval_for_auto_marked",
                    models.BooleanField(
                        default=False,
                        help_text="Require moderator approval for auto-marked spoiler reviews",
                    ),
                ),
                (
                    "send_to_moderation_queue_threshold",
                    models.FloatField(
                        default=0.6,
                        help_text="Confidence threshold for sending reviews to moderation queue",
                    ),
                ),
                (
                    "notify_moderators_on_auto_mark",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications when reviews are auto-marked",
                    ),
                ),
                (
                    "daily_report_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send daily performance reports to administrators",
                    ),
                ),
                (
                    "accuracy_target",
                    models.FloatField(
                        default=0.85,
                        help_text="Target accuracy rate for the spoiler detection system",
                    ),
                ),
                (
                    "false_positive_limit",
                    models.FloatField(
                        default=0.1, help_text="Maximum acceptable false positive rate"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is currently active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrator who created this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Configuration",
                "verbose_name_plural": "Moderation Configurations",
                "db_table": "movies_moderation_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_confidence",
                    models.FloatField(
                        help_text="Original spoiler detection confidence score"
                    ),
                ),
                (
                    "original_suggested_action",
                    models.CharField(
                        help_text="Original suggested action from spoiler detection",
                        max_length=32,
                    ),
                ),
                (
                    "original_is_spoiler",
                    models.BooleanField(help_text="Original spoiler detection result"),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("correct_spoiler", "Correctly Marked as Spoiler"),
                            ("false_positive", "False Positive - Not a Spoiler"),
                            ("missed_spoiler", "False Negative - Missed Spoiler"),
                            ("correct_non_spoiler", "Correctly Marked as Non-Spoiler"),
                        ],
                        help_text="Type of feedback provided by moderator",
                        max_length=32,
                    ),
                ),
                (
                    "moderator_decision",
                    models.CharField(
                        choices=[
                            ("approve_as_spoiler", "Approve as Spoiler"),
                            ("approve_as_non_spoiler", "Approve as Non-Spoiler"),
                            ("reject_review", "Reject Review"),
                            ("request_revision", "Request Revision"),
                        ],
                        help_text="Final decision made by moderator",
                        max_length=32,
                    ),
                ),
                (
                    "is_spoiler_correct",
                    models.BooleanField(
                        help_text="Whether the spoiler detection was correct according to moderator"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes from moderator explaining the decision",
                        null=True,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy to Detect"),
                            ("medium", "Medium Difficulty"),
                            ("hard", "Hard to Detect"),
                            ("ambiguous", "Ambiguous Case"),
                        ],
                        default="medium",
                        help_text="Subjective difficulty of spoiler detection for this review",
                        max_length=20,
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time spent by moderator reviewing this item (in seconds)",
                        null=True,
                    ),
                ),
                (
                    "used_for_learning",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feedback has been used to update the learning algorithm",
                    ),
                ),
                (
                    "learning_impact_score",
                    models.FloatField(
                        blank=True,
                        help_text="Calculated impact score of this feedback on system learning",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        help_text="The moderator who provided feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spoiler_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="The review that was moderated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_feedback",
                        to="movies.moviereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Feedback",
                "verbose_name_plural": "Moderation Feedback",
                "db_table": "movies_moderation_feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["review"], name="movies_mode_review__c90071_idx"
                    ),
                    models.Index(
                        fields=["moderator"], name="movies_mode_moderat_aae06b_idx"
                    ),
                    models.Index(
                        fields=["feedback_type"], name="movies_mode_feedbac_5caa20_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="movies_mode_created_8b091e_idx"
                    ),
                    models.Index(
                        fields=["used_for_learning"],
                        name="movies_mode_used_fo_bed459_idx",
                    ),
                    models.Index(
                        fields=["is_spoiler_correct"],
                        name="movies_mode_is_spoi_354bce_idx",
                    ),
                    models.Index(
                        fields=["original_confidence"],
                        name="movies_mode_origina_f8be89_idx",
                    ),
                    models.Index(
                        fields=["feedback_type", "created_at"],
                        name="movies_mode_feedbac_4bab80_idx",
                    ),
                    models.Index(
                        fields=["moderator", "created_at"],
                        name="movies_mode_moderat_d081f8_idx",
                    ),
                    models.Index(
                        fields=["original_confidence", "is_spoiler_correct"],
                        name="movies_mode_origina_27d894_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="moderationfeedback",
            constraint=models.UniqueConstraint(
                fields=("review", "moderator"), name="unique_review_moderator_feedback"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationconfig",
            index=models.Index(
                fields=["is_active"], name="movies_mode_is_acti_d35421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationconfig",
            index=models.Index(
                fields=["created_at"], name="movies_mode_created_80468d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationconfig",
            index=models.Index(
                fields=["updated_at"], name="movies_mode_updated_cd0286_idx"
            ),
        ),
    ]
