# Generated by Django 4.2.21 on 2025-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0034_add_moderation_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["review_type", "is_public", "is_approved", "created_at"],
                name="idx_moderation_queue_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["is_spoiler", "created_at", "language"],
                name="idx_spoiler_detection_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["review_type", "is_public", "created_at"],
                name="idx_reports_moderation_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["is_approved", "moderated_at"], name="idx_moderation_status"
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                condition=models.Q(
                    ("is_approved__isnull", True),
                    ("is_public", True),
                    ("review_type", "USER"),
                ),
                fields=["created_at"],
                name="idx_pending_moderation",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                condition=models.Q(("is_spoiler", True), ("review_type", "USER")),
                fields=["created_at"],
                name="idx_spoiler_reviews",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["review", "created_at"], name="idx_review_reports_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["reason", "created_at"], name="idx_reports_reason_date"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["review", "reason"], name="idx_review_reason_reports"
            ),
        ),
    ]
