# Generated by Django 4.2.21 on 2025-07-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0035_add_moderation_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homepage_views",
                    models.IntegerField(
                        default=0, help_text="Views on homepage/landing page"
                    ),
                ),
                (
                    "detail_page_views",
                    models.IntegerField(
                        default=0, help_text="Views on movie detail page"
                    ),
                ),
                (
                    "trailer_plays",
                    models.IntegerField(default=0, help_text="Number of trailer plays"),
                ),
                (
                    "search_appearances",
                    models.IntegerField(
                        default=0, help_text="Times appeared in search results"
                    ),
                ),
                (
                    "click_through_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="CTR from homepage to detail page (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "engagement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overall engagement rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "trailer_completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Trailer completion rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "mobile_views",
                    models.IntegerField(
                        default=0, help_text="Views from mobile devices"
                    ),
                ),
                (
                    "desktop_views",
                    models.IntegerField(default=0, help_text="Views from desktop"),
                ),
                (
                    "tablet_views",
                    models.IntegerField(default=0, help_text="Views from tablet"),
                ),
                (
                    "last_featured_date",
                    models.DateTimeField(
                        blank=True, help_text="Last time movie was featured", null=True
                    ),
                ),
                (
                    "total_featured_days",
                    models.IntegerField(
                        default=0, help_text="Total days movie was featured"
                    ),
                ),
                (
                    "first_published_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="First time movie was published",
                        null=True,
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated performance score (0-100)",
                        max_digits=4,
                    ),
                ),
                (
                    "trending_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Trending score based on recent activity",
                        max_digits=4,
                    ),
                ),
                (
                    "region_performance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Performance breakdown by region",
                    ),
                ),
                (
                    "language_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User language preferences for this movie",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, help_text="Total user reviews"),
                ),
                (
                    "average_user_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Average user rating",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "positive_review_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of positive reviews",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_metrics_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time metrics were calculated",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Metrics",
                "verbose_name_plural": "Production Metrics",
                "db_table": "movies_production_metrics",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="admin_featured",
            field=models.BooleanField(
                default=False, help_text="Admin manually featured"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="admin_priority",
            field=models.IntegerField(
                default=0, help_text="Admin priority (higher = more important)"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="age_rating",
            field=models.CharField(
                blank=True, help_text="Phân loại độ tuổi", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ duyệt"),
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Từ chối"),
                    ("NEEDS_REVIEW", "Cần xem xét"),
                ],
                default="APPROVED",
                help_text="Trạng thái duyệt của phim",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian duyệt", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người duyệt phim",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="content_completeness",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% hoàn thiện content",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="content_warnings",
            field=models.JSONField(
                blank=True, default=list, help_text="Cảnh báo nội dung"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="featured_from",
            field=models.DateTimeField(
                blank=True, help_text="Bắt đầu featured", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="featured_until",
            field=models.DateTimeField(
                blank=True, help_text="Kết thúc featured", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_published",
            field=models.BooleanField(
                default=True, help_text="Hiển thị phim trên production"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="manual_override",
            field=models.JSONField(
                blank=True, default=dict, help_text="Admin override settings"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="minimum_quality_met",
            field=models.BooleanField(
                default=True, help_text="Đạt tiêu chuẩn chất lượng tối thiểu"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="publish_date",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian xuất bản", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="quality_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Điểm chất lượng content (0-10)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="target_regions",
            field=models.JSONField(
                blank=True, default=list, help_text="Danh sách regions hiển thị"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="unpublish_date",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian ngừng hiển thị", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="visibility_status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Công khai"),
                    ("DRAFT", "Bản nháp"),
                    ("SCHEDULED", "Đã lên lịch"),
                    ("ARCHIVED", "Lưu trữ"),
                    ("RESTRICTED", "Hạn chế"),
                ],
                default="PUBLISHED",
                help_text="Trạng thái hiển thị của phim",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["is_published"], name="idx_movie_is_published"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["visibility_status"], name="idx_movie_visibility_status"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["approval_status"], name="idx_movie_approval_status"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["admin_featured"], name="idx_movie_admin_featured"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["admin_priority"], name="idx_movie_admin_priority"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["minimum_quality_met"], name="idx_movie_min_quality"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["publish_date"], name="idx_movie_publish_date"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["unpublish_date"], name="idx_movie_unpublish_date"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["featured_from"], name="idx_movie_featured_from"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["featured_until"], name="idx_movie_featured_until"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["approved_at"], name="idx_movie_approved_at"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["quality_score"], name="idx_movie_quality_score"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["content_completeness"], name="idx_movie_content_completeness"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["is_published", "approval_status", "visibility_status"],
                name="idx_movie_production_ready",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["admin_featured", "admin_priority", "featured_from"],
                name="idx_movie_admin_schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["minimum_quality_met", "quality_score", "content_completeness"],
                name="idx_movie_quality_filter",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(
                    ("approval_status", "APPROVED"),
                    ("is_published", True),
                    ("minimum_quality_met", True),
                    ("visibility_status", "PUBLISHED"),
                ),
                fields=["admin_priority", "combined_rating_score"],
                name="idx_movie_production_visible",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(("admin_featured", True), ("is_published", True)),
                fields=["admin_priority", "featured_from"],
                name="idx_movie_admin_active",
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="movie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_metrics",
                to="movies.movie",
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(fields=["movie"], name="movies_prod_movie_i_3ce87b_idx"),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["performance_score"], name="idx_metrics_performance"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(fields=["trending_score"], name="idx_metrics_trending"),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(fields=["click_through_rate"], name="idx_metrics_ctr"),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["engagement_rate"], name="idx_metrics_engagement"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["last_featured_date"], name="idx_metrics_last_featured"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["total_featured_days"], name="idx_metrics_featured_days"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["homepage_views"], name="idx_metrics_homepage_views"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["detail_page_views"], name="idx_metrics_detail_views"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(fields=["updated_at"], name="idx_metrics_updated"),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["performance_score", "trending_score"],
                name="idx_metrics_scores",
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["homepage_views", "click_through_rate"],
                name="idx_metrics_homepage",
            ),
        ),
    ]
