# Generated by Django 4.2.21 on 2025-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0036_add_production_control_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ duyệt"),
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Từ chối"),
                    ("NEEDS_REVIEW", "Cần xem xét"),
                ],
                default="PENDING",
                help_text="Trạng thái duyệt của phim",
                max_length=20,
            ),
        ),
    ]
