# Generated by Django 4.2.21 on 2025-07-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0037_fix_approval_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieAdminControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ duyệt"),
                            ("APPROVED", "Đã duyệt"),
                            ("REJECTED", "Từ chối"),
                            ("NEEDS_REVIEW", "Cần xem xét"),
                        ],
                        default="PENDING",
                        help_text="Trạng thái duyệt của phim",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian duyệt", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Lý do từ chối", null=True),
                ),
                (
                    "visibility_status",
                    models.CharField(
                        choices=[
                            ("PUBLISHED", "Công khai"),
                            ("DRAFT", "Bản nháp"),
                            ("SCHEDULED", "Đã lên lịch"),
                            ("ARCHIVED", "Lưu trữ"),
                            ("RESTRICTED", "Hạn chế"),
                            ("HIDDEN", "Ẩn"),
                        ],
                        default="PUBLISHED",
                        help_text="Trạng thái hiển thị của phim",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Hiển thị phim trên production"
                    ),
                ),
                (
                    "admin_featured",
                    models.BooleanField(
                        default=False, help_text="Admin manually featured"
                    ),
                ),
                (
                    "admin_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Admin priority (0-10, higher = more important)",
                    ),
                ),
                (
                    "manual_override",
                    models.JSONField(
                        blank=True, default=dict, help_text="Admin override settings"
                    ),
                ),
                (
                    "target_regions",
                    models.JSONField(
                        blank=True, default=list, help_text="Danh sách regions hiển thị"
                    ),
                ),
                (
                    "age_rating",
                    models.CharField(
                        blank=True,
                        help_text="Phân loại độ tuổi",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "content_warnings",
                    models.JSONField(
                        blank=True, default=list, help_text="Cảnh báo nội dung"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người duyệt phim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_movies_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin tạo control record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin sửa đổi cuối",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_admin_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_control",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Admin Control",
                "verbose_name_plural": "Movie Admin Controls",
                "db_table": "movies_admin_control",
                "indexes": [
                    models.Index(
                        fields=["approval_status"], name="idx_admin_approval_status"
                    ),
                    models.Index(
                        fields=["visibility_status"], name="idx_admin_visibility_status"
                    ),
                    models.Index(fields=["admin_featured"], name="idx_admin_featured"),
                    models.Index(fields=["admin_priority"], name="idx_admin_priority"),
                    models.Index(fields=["is_published"], name="idx_admin_published"),
                    models.Index(
                        fields=["approval_status", "visibility_status"],
                        name="idx_admin_approval_visibility",
                    ),
                    models.Index(
                        fields=["admin_featured", "admin_priority"],
                        name="idx_admin_featured_priority",
                    ),
                    models.Index(
                        fields=["is_published", "approval_status"],
                        name="idx_admin_published_approval",
                    ),
                    models.Index(fields=["created_by"], name="idx_admin_created_by"),
                    models.Index(
                        fields=["last_modified_by"], name="idx_admin_modified_by"
                    ),
                    models.Index(fields=["updated_at"], name="idx_admin_updated_at"),
                    models.Index(fields=["approved_at"], name="idx_admin_approved_at"),
                    models.Index(fields=["created_at"], name="idx_admin_created_at"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="movieadmincontrol",
            constraint=models.CheckConstraint(
                check=models.Q(("admin_priority__gte", 0), ("admin_priority__lte", 10)),
                name="check_admin_priority_range",
            ),
        ),
    ]
