# Generated by Django 4.2.21 on 2025-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0038_create_admin_control_table"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movieadmincontrol",
            index=models.Index(
                fields=["created_at", "approval_status"], name="idx_admin_cr_approval"
            ),
        ),
        migrations.AddIndex(
            model_name="movieadmincontrol",
            index=models.Index(
                fields=["updated_at", "visibility_status"], name="idx_admin_upd_vis"
            ),
        ),
        migrations.AddIndex(
            model_name="movieadmincontrol",
            index=models.Index(
                fields=["admin_priority", "admin_featured"], name="idx_admin_pri_feat"
            ),
        ),
        migrations.AddIndex(
            model_name="movieadmincontrol",
            index=models.Index(
                fields=["is_published", "visibility_status", "approval_status"],
                name="idx_admin_pub_vis_app",
            ),
        ),
    ]
