# Generated by Django 4.2.21 on 2025-07-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0039_movieadmincontrol_idx_admin_cr_approval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieQualityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Điểm chất lượng content (0.0-10.0)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "content_completeness",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% hoàn thiện content (0.00-100.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "minimum_quality_met",
                    models.BooleanField(
                        default=True, help_text="Đạt tiêu chuẩn chất lượng tối thiểu"
                    ),
                ),
                (
                    "basic_info_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Điểm thông tin cơ bản (title, overview, date)",
                        max_digits=3,
                    ),
                ),
                (
                    "visual_assets_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Điểm tài sản hình ảnh (poster, backdrop)",
                        max_digits=3,
                    ),
                ),
                (
                    "metadata_richness_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Điểm độ phong phú metadata (cast, trailer, keywords)",
                        max_digits=3,
                    ),
                ),
                (
                    "rating_validity_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Điểm tính hợp lệ của rating",
                        max_digits=3,
                    ),
                ),
                (
                    "quality_issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách các vấn đề chất lượng được phát hiện",
                    ),
                ),
                (
                    "quality_suggestions",
                    models.JSONField(
                        blank=True, default=list, help_text="Gợi ý cải thiện chất lượng"
                    ),
                ),
                (
                    "last_quality_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="Lần kiểm tra chất lượng cuối cùng",
                        null=True,
                    ),
                ),
                (
                    "auto_calculated",
                    models.BooleanField(
                        default=True, help_text="Được tính toán tự động bởi hệ thống"
                    ),
                ),
                (
                    "calculation_version",
                    models.CharField(
                        default="1.0",
                        help_text="Phiên bản thuật toán tính toán",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_metrics",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Quality Metrics",
                "verbose_name_plural": "Movie Quality Metrics",
                "db_table": "movies_quality_metrics",
            },
        ),
        migrations.CreateModel(
            name="MovieScheduling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian xuất bản", null=True
                    ),
                ),
                (
                    "unpublish_date",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian ngừng hiển thị", null=True
                    ),
                ),
                (
                    "auto_publish",
                    models.BooleanField(
                        default=False,
                        help_text="Tự động xuất bản vào thời điểm đã lên lịch",
                    ),
                ),
                (
                    "auto_unpublish",
                    models.BooleanField(
                        default=False,
                        help_text="Tự động ngừng hiển thị vào thời điểm đã lên lịch",
                    ),
                ),
                (
                    "featured_from",
                    models.DateTimeField(
                        blank=True, help_text="Bắt đầu featured", null=True
                    ),
                ),
                (
                    "featured_until",
                    models.DateTimeField(
                        blank=True, help_text="Kết thúc featured", null=True
                    ),
                ),
                (
                    "auto_feature",
                    models.BooleanField(
                        default=False,
                        help_text="Tự động featured vào thời điểm đã lên lịch",
                    ),
                ),
                (
                    "auto_unfeature",
                    models.BooleanField(
                        default=False,
                        help_text="Tự động bỏ featured vào thời điểm đã lên lịch",
                    ),
                ),
                (
                    "recurring_pattern",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mẫu lặp lại cho nội dung theo mùa",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="Múi giờ cho lịch trình", max_length=50
                    ),
                ),
                (
                    "next_scheduled_action",
                    models.CharField(
                        blank=True,
                        help_text="Hành động được lên lịch tiếp theo (publish, unpublish, feature, unfeature)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "next_action_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Thời gian thực hiện hành động tiếp theo",
                        null=True,
                    ),
                ),
                (
                    "last_action_executed",
                    models.CharField(
                        blank=True,
                        help_text="Hành động cuối cùng được thực hiện",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_action_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Thời gian thực hiện hành động cuối cùng",
                        null=True,
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        blank=True,
                        help_text="Tên chiến dịch marketing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("marketing", "Marketing Campaign"),
                            ("seasonal", "Seasonal Campaign"),
                            ("special", "Special Event"),
                            ("promotion", "Promotion"),
                            ("launch", "Movie Launch"),
                        ],
                        help_text="Loại chiến dịch",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "campaign_priority",
                    models.IntegerField(
                        default=0, help_text="Độ ưu tiên chiến dịch (0-10)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Scheduling",
                "verbose_name_plural": "Movie Scheduling",
                "db_table": "movies_scheduling",
                "indexes": [
                    models.Index(
                        fields=["publish_date"], name="idx_sched_publish_date"
                    ),
                    models.Index(
                        fields=["unpublish_date"], name="idx_sched_unpublish_date"
                    ),
                    models.Index(
                        fields=["auto_publish"], name="idx_sched_auto_publish"
                    ),
                    models.Index(
                        fields=["auto_unpublish"], name="idx_sched_auto_unpublish"
                    ),
                    models.Index(
                        fields=["featured_from"], name="idx_sched_featured_from"
                    ),
                    models.Index(
                        fields=["featured_until"], name="idx_sched_featured_until"
                    ),
                    models.Index(
                        fields=["auto_feature"], name="idx_sched_auto_feature"
                    ),
                    models.Index(
                        fields=["auto_unfeature"], name="idx_sched_auto_unfeature"
                    ),
                    models.Index(
                        fields=["next_action_date"], name="idx_sched_next_action"
                    ),
                    models.Index(
                        fields=["next_scheduled_action"], name="idx_sched_next_act_type"
                    ),
                    models.Index(
                        fields=["last_action_date"], name="idx_sched_last_action"
                    ),
                    models.Index(fields=["campaign_name"], name="idx_sched_campaign"),
                    models.Index(
                        fields=["campaign_type"], name="idx_sched_campaign_type"
                    ),
                    models.Index(
                        fields=["campaign_priority"], name="idx_sched_camp_priority"
                    ),
                    models.Index(
                        fields=["publish_date", "unpublish_date"],
                        name="idx_sched_publish_window",
                    ),
                    models.Index(
                        fields=["featured_from", "featured_until"],
                        name="idx_sched_featured_window",
                    ),
                    models.Index(
                        fields=["campaign_type", "campaign_priority"],
                        name="idx_sched_camp_type_pri",
                    ),
                    models.Index(fields=["updated_at"], name="idx_sched_updated"),
                    models.Index(fields=["created_at"], name="idx_sched_created"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="moviescheduling",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("campaign_priority__gte", 0), ("campaign_priority__lte", 10)
                ),
                name="check_campaign_priority_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviescheduling",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("publish_date__isnull", True),
                    ("unpublish_date__isnull", True),
                    ("publish_date__lt", models.F("unpublish_date")),
                    _connector="OR",
                ),
                name="check_publish_unpublish_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviescheduling",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("featured_from__isnull", True),
                    ("featured_until__isnull", True),
                    ("featured_from__lt", models.F("featured_until")),
                    _connector="OR",
                ),
                name="check_featured_from_until_order",
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(fields=["quality_score"], name="idx_quality_score"),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["content_completeness"], name="idx_quality_completeness"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["minimum_quality_met"], name="idx_quality_minimum_met"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["basic_info_score"], name="idx_quality_basic_info"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["visual_assets_score"], name="idx_quality_visual"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["metadata_richness_score"], name="idx_quality_metadata"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["rating_validity_score"], name="idx_quality_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["quality_score", "content_completeness"],
                name="idx_quality_score_completeness",
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["minimum_quality_met", "quality_score"],
                name="idx_quality_met_score",
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["auto_calculated"], name="idx_quality_auto_calc"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["last_quality_check"], name="idx_quality_last_check"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                fields=["calculation_version"], name="idx_quality_calc_version"
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(fields=["updated_at"], name="idx_quality_updated"),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(fields=["created_at"], name="idx_quality_created"),
        ),
        migrations.AddConstraint(
            model_name="moviequalitymetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("quality_score__gte", 0.0), ("quality_score__lte", 10.0)
                ),
                name="check_quality_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviequalitymetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("content_completeness__gte", 0.0),
                    ("content_completeness__lte", 100.0),
                ),
                name="check_content_completeness_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviequalitymetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("basic_info_score__gte", 0.0), ("basic_info_score__lte", 10.0)
                ),
                name="check_basic_info_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviequalitymetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("visual_assets_score__gte", 0.0),
                    ("visual_assets_score__lte", 10.0),
                ),
                name="check_visual_assets_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviequalitymetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("metadata_richness_score__gte", 0.0),
                    ("metadata_richness_score__lte", 10.0),
                ),
                name="check_metadata_richness_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviequalitymetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("rating_validity_score__gte", 0.0),
                    ("rating_validity_score__lte", 10.0),
                ),
                name="check_rating_validity_score_range",
            ),
        ),
    ]
