# Generated by Django 4.2.21 on 2025-07-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0040_create_quality_and_scheduling_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session ID for anonymous users",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Type of interaction (view, click, favorite, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        blank=True,
                        help_text="Specific interaction type from metadata",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("page_url", models.URLField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "screen_resolution",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "viewport_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this interaction was processed for metrics",
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time spent on page/interaction",
                        null=True,
                    ),
                ),
                (
                    "is_unique_session",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the first interaction from this session",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="movies.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movie_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "movies_userinteraction",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["movie", "action", "timestamp"],
                        name="movies_user_movie_i_5d4a09_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="movies_user_user_id_cec555_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="movies_user_session_879df9_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="movies_user_action_75c9bd_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="movies_user_timesta_bc4a6b_idx"
                    ),
                    models.Index(
                        fields=["processed_at"], name="movies_user_process_2303e7_idx"
                    ),
                ],
            },
        ),
    ]
