# Generated by Django 4.2.21 on 2025-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0041_add_user_interaction_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionmetrics",
            name="bounce_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage of users who left quickly",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="last_interaction_date",
            field=models.DateTimeField(
                blank=True, help_text="Last time there was user interaction", null=True
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="return_visitor_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage of returning visitors",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="session_duration_avg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Average session duration in seconds",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="user_favorites_count",
            field=models.IntegerField(
                default=0, help_text="Number of users who favorited this movie"
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="user_likes_count",
            field=models.IntegerField(default=0, help_text="Number of user likes"),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="user_shares_count",
            field=models.IntegerField(
                default=0, help_text="Number of times movie was shared"
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="user_watchlist_count",
            field=models.IntegerField(
                default=0, help_text="Number of users who added to watchlist"
            ),
        ),
    ]
