# Generated by Django 4.2.21 on 2025-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0042_add_production_metrics_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionmetrics",
            name="trending_category",
            field=models.CharField(
                choices=[
                    ("viral", "Viral"),
                    ("hot", "Hot"),
                    ("rising", "Rising"),
                    ("stable", "Stable"),
                ],
                db_index=True,
                default="stable",
                help_text="Trending category based on recent activity",
                max_length=20,
            ),
        ),
    ]
