# Generated by Django 4.2.21 on 2025-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0043_productionmetrics_trending_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productionmetrics",
            name="idx_metrics_featured_days",
        ),
        migrations.RenameField(
            model_name="productionmetrics",
            old_name="last_metrics_update",
            new_name="last_calculated_at",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="bounce_rate",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="first_published_date",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="language_preferences",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="positive_review_ratio",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="region_performance",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="return_visitor_rate",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="search_appearances",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="session_duration_avg",
        ),
        migrations.RemoveField(
            model_name="productionmetrics",
            name="total_featured_days",
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="auto_calculated",
            field=models.BooleanField(
                default=True, help_text="Whether metrics were calculated automatically"
            ),
        ),
        migrations.AddField(
            model_name="productionmetrics",
            name="calculation_version",
            field=models.CharField(
                default="2.0",
                help_text="Version of calculation algorithm used",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["trending_category"], name="idx_metrics_trending_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["last_calculated_at"], name="idx_metrics_last_calculated"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmetrics",
            index=models.Index(
                fields=["trending_category", "trending_score"],
                name="idx_metrics_trending_combo",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionmetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("performance_score__gte", 0), ("performance_score__lte", 100)
                ),
                name="performance_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionmetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("trending_score__gte", 0), ("trending_score__lte", 100)
                ),
                name="trending_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionmetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("click_through_rate__gte", 0), ("click_through_rate__lte", 100)
                ),
                name="ctr_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionmetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("engagement_rate__gte", 0), ("engagement_rate__lte", 100)
                ),
                name="engagement_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionmetrics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("trailer_completion_rate__gte", 0),
                    ("trailer_completion_rate__lte", 100),
                ),
                name="trailer_completion_rate_range",
            ),
        ),
    ]
