# Generated by Django 4.2.21 on 2025-07-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0044_remove_unused_production_metrics_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviereview",
            name="reply_to_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User being replied to when replying to a reply (for @mentions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentioned_in_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                fields=["reply_to_user"], name="movies_revi_reply_t_3a0c28_idx"
            ),
        ),
    ]
