# Generated by Django 4.2.21 on 2025-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0045_moviereview_reply_to_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieadmincontrol",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Hiển thị phim trên production"
            ),
        ),
        migrations.AlterField(
            model_name="movieadmincontrol",
            name="visibility_status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Công khai"),
                    ("DRAFT", "Bản nháp"),
                    ("SCHEDULED", "Đã lên lịch"),
                    ("ARCHIVED", "Lưu trữ"),
                    ("RESTRICTED", "Hạn chế"),
                    ("HIDDEN", "Ẩn"),
                ],
                default="DRAFT",
                help_text="Trạng thái hiển thị của phim",
                max_length=20,
            ),
        ),
    ]
