# Generated by Django 4.2.21 on 2025-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0047_remove_movie_idx_movie_is_published_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                condition=models.Q(
                    ("poster_url__isnull", False),
                    ("poster_url__gt", ""),
                    ("title__gt", ""),
                ),
                fields=["poster_url", "is_adult", "title", "combined_rating_score"],
                name="idx_mv_pstr_adlt_ttl_rt",
            ),
        ),
        migrations.AddIndex(
            model_name="moviequalitymetrics",
            index=models.Index(
                condition=models.Q(("minimum_quality_met", True)),
                fields=["movie"],
                name="idx_quality_minimum_met_true",
            ),
        ),
    ]
