# Generated by Django 4.2.21 on 2025-07-28 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0048_movie_idx_mv_pstr_adlt_ttl_rt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movienews",
            name="movie",
        ),
        migrations.DeleteModel(
            name="MovieAward",
        ),
        migrations.DeleteModel(
            name="MovieNews",
        ),
    ]
