# Generated by Django 4.2.21 on 2025-07-31 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0049_remove_movie_award"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movierating",
            name="movies_rati_metacri_b6685f_idx",
        ),
        migrations.RemoveIndex(
            model_name="movierating",
            name="movies_rati_rotten__9caa34_idx",
        ),
        migrations.RemoveField(
            model_name="movierating",
            name="film_affinity_rating",
        ),
        migrations.RemoveField(
            model_name="movierating",
            name="film_affinity_votes",
        ),
        migrations.RemoveField(
            model_name="movierating",
            name="metacritic_rating",
        ),
        migrations.RemoveField(
            model_name="movierating",
            name="rotten_tomatoes_rating",
        ),
        migrations.RemoveField(
            model_name="movierating",
            name="rotten_tomatoes_votes",
        ),
        migrations.RemoveField(
            model_name="moviereview",
            name="source_url",
        ),
    ]
