# Generated by Django 4.2.21 on 2025-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0050_remove_movierating_movies_rati_metacri_b6685f_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movieadmincontrol",
            name="target_regions",
        ),
        migrations.AlterField(
            model_name="moviereview",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Rating scale 1.0-5.0 (5-star system, whole numbers only)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                condition=models.Q(
                    ("is_approved__isnull", True),
                    ("is_public", True),
                    ("review_type", "USER"),
                ),
                fields=["review_type", "is_public", "is_approved", "created_at"],
                name="idx_ultra_moderation_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                condition=models.Q(
                    ("is_approved__isnull", True),
                    ("is_public", True),
                    ("review_type", "USER"),
                ),
                fields=[
                    "review_type",
                    "is_public",
                    "is_approved",
                    "is_spoiler",
                    "created_at",
                ],
                name="idx_ultra_high_priority",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                condition=models.Q(
                    ("is_approved__isnull", True),
                    ("is_public", True),
                    ("review_type", "USER"),
                ),
                fields=[
                    "review_type",
                    "is_public",
                    "is_approved",
                    "language",
                    "created_at",
                ],
                name="idx_ultra_language_filter",
            ),
        ),
        migrations.AddIndex(
            model_name="moviereview",
            index=models.Index(
                condition=models.Q(
                    ("is_approved__isnull", True),
                    ("is_public", True),
                    ("review_type", "USER"),
                ),
                fields=["review_type", "is_public", "is_approved", "created_at"],
                name="idx_ultra_date_range",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["review", "reason"], name="idx_ultra_report_reason"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(fields=["review"], name="idx_ultra_report_count"),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                condition=models.Q(("reason__in", ["abuse", "offensive"])),
                fields=["review", "reason", "created_at"],
                name="idx_ultra_abuse_reports",
            ),
        ),
    ]
