# Generated by Django 4.2.21 on 2025-08-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0051_remove_movieadmincontrol_target_regions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviescheduling",
            name="timezone",
            field=models.CharField(
                default="Asia/Ho_Chi_Minh",
                help_text="Múi giờ cho lịch trình",
                max_length=50,
            ),
        ),
    ]
