# Generated by Django 5.1.7 on 2025-03-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecrew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='movies.movie'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='metadata_pe_name_e78f13_idx'),
        ),
        migrations.AddField(
            model_name='moviecrew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_roles', to='metadata.person'),
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['movie', 'role'], name='metadata_mo_movie_i_06157a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'person', 'role', 'character_name')},
        ),
    ]
